// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoleBased.Infrastructure.Persistance;

#nullable disable

namespace RoleBased.Infrastructure.Migrations
{
    [DbContext(typeof(ReoleBasedDbContext))]
    [Migration("20231003040212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoleBased.Model.LoginDb", b =>
                {
                    b.Property<string>("RegNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegNo");

                    b.ToTable("LoginDb");
                });

            modelBuilder.Entity("RoleBased.Model.StudentInfo", b =>
                {
                    b.Property<string>("RegNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DoB")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RegNo");

                    b.ToTable("StudentInfo");

                    b.HasData(
                        new
                        {
                            RegNo = "1",
                            Created = new DateTimeOffset(new DateTime(2023, 10, 3, 10, 2, 12, 492, DateTimeKind.Unspecified).AddTicks(1192), new TimeSpan(0, 6, 0, 0, 0)),
                            CreatedBy = "1",
                            DoB = new DateTimeOffset(new DateTime(2023, 10, 3, 10, 2, 12, 492, DateTimeKind.Unspecified).AddTicks(1157), new TimeSpan(0, 6, 0, 0, 0)),
                            EmailNo = "pejus4490@gmail.Com",
                            LastModified = new DateTimeOffset(new DateTime(2023, 10, 3, 10, 2, 12, 492, DateTimeKind.Unspecified).AddTicks(1194), new TimeSpan(0, 6, 0, 0, 0)),
                            Name = "Pejus Kanti Sazzon",
                            PhoneNo = "01650xxxx",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
